services:
  mongo-db:
    image: mongo:4.2
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - '27018'
    ports:
      - '27018:27018'
    networks:
      - default

  orion:
    image: fiware/orion:3.6.0
    ports:
      - "1026:1026"
    command: -dbhost mongo

  mosquitto:
    image: eclipse-mosquitto:2.0.15
    ports:
      - "1883:1883"
      - "9001:9001"

  iot-agent:
    image: quay.io/fiware/iotagent-ul:latest
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
      - mongo-db
    networks:
      - default
    expose:
      - '4041'
      - '7896'
    ports:
      - '4041:4041'
      - '7896:7896'
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_TIMESTAMP=true
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_AUTOCAST=true
      - IOTA_MONGO_HOST=mongo
      - IOTA_MONGO_PORT=27018
      - IOTA_MONGO_DB=iotagentul
      - IOTA_HTTP_PORT=7896
      - IOTA_PROVIDER_URL=http://iot-agent:4041